spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/"
      database: "police-event-sweden"

---

spring:
  data:
    mongodb:
      uri: ""
      database: "police-event-sweden"
  config:
    activate:
      on-profile: live